//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        public int USER_ID { get; set; }
        public string ITEMS { get; set; }
    
        public virtual User User { get; set; }
    }
}
