//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_Forum
    {
        public int ForumID { get; set; }
        public string ForumSubID { get; set; }
        public string ForumHost { get; set; }
        public string ForumName { get; set; }
    }
}
