//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food()
        {
            this.ingredients = new HashSet<ingredients>();
            this.nutvalues = new HashSet<nutvalues>();
            this.missinglistdetails = new HashSet<missinglistdetails>();
            this.savedlistdetails = new HashSet<savedlistdetails>();
        }
    
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public int FoodCategoryId { get; set; }
        public int CalculateUnitId { get; set; }
        public bool IsTemporary { get; set; }
        public string Remarks { get; set; }
        public int SortOrder { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool PrintPicture { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual users users { get; set; }
        public virtual foodcategories foodcategories { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingredients> ingredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nutvalues> nutvalues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<missinglistdetails> missinglistdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<savedlistdetails> savedlistdetails { get; set; }
    }
}
