//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredients
    {
        public int IngredientId { get; set; }
        public int RecipeId { get; set; }
        public int FoodId { get; set; }
        public int MeasurementUnitId { get; set; }
        public decimal Quantity { get; set; }
        public string Remarks { get; set; }
        public int SortOrder { get; set; }
    
        public virtual food food { get; set; }
        public virtual measurementunits measurementunits { get; set; }
    }
}
