//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class mealrecipes
    {
        public int MealId { get; set; }
        public int RecipeId { get; set; }
        public int Servings { get; set; }
    
        public virtual meals meals { get; set; }
        public virtual recipes recipes { get; set; }
    }
}
