//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meal()
        {
            this.MealRecipes = new HashSet<MealRecipe>();
        }
    
        public int MealId { get; set; }
        public int MenuId { get; set; }
        public int MealTypeId { get; set; }
        public Nullable<int> DayIndex { get; set; }
        public Nullable<int> CourseTypeId { get; set; }
        public Nullable<int> Diners { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Comments { get; set; }
    
        public virtual CourseType CourseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealRecipe> MealRecipes { get; set; }
        public virtual MealType MealType { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
