//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasurementUnitsConvert
    {
        public int ConvertId { get; set; }
        public int FoodId { get; set; }
        public int FromUnitId { get; set; }
        public decimal FromQuantity { get; set; }
        public int ToUnitId { get; set; }
        public decimal ToQuantity { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MeasurementUnit MeasurementUnit { get; set; }
    }
}
