//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mybuylistEntities : DbContext
    {
        public mybuylistEntities()
            : base("name=mybuylistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articles> articles { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<coursetypes> coursetypes { get; set; }
        public virtual DbSet<food> food { get; set; }
        public virtual DbSet<foodcategories> foodcategories { get; set; }
        public virtual DbSet<generalitems> generalitems { get; set; }
        public virtual DbSet<ingredients> ingredients { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<mblsettings> mblsettings { get; set; }
        public virtual DbSet<mcategories> mcategories { get; set; }
        public virtual DbSet<mealrecipes> mealrecipes { get; set; }
        public virtual DbSet<meals> meals { get; set; }
        public virtual DbSet<mealtypes> mealtypes { get; set; }
        public virtual DbSet<measurementunits> measurementunits { get; set; }
        public virtual DbSet<measurementunitsconverts> measurementunitsconverts { get; set; }
        public virtual DbSet<menus> menus { get; set; }
        public virtual DbSet<menutypes> menutypes { get; set; }
        public virtual DbSet<missinglistdetails> missinglistdetails { get; set; }
        public virtual DbSet<missinglists> missinglists { get; set; }
        public virtual DbSet<nutcategories> nutcategories { get; set; }
        public virtual DbSet<nutitems> nutitems { get; set; }
        public virtual DbSet<nutvalues> nutvalues { get; set; }
        public virtual DbSet<recieplist> recieplist { get; set; }
        public virtual DbSet<recieplistdetails> recieplistdetails { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
        public virtual DbSet<recipesinshoppinglist> recipesinshoppinglist { get; set; }
        public virtual DbSet<savedlist> savedlist { get; set; }
        public virtual DbSet<savedlistdetails> savedlistdetails { get; set; }
        public virtual DbSet<shopdepartments> shopdepartments { get; set; }
        public virtual DbSet<shoppinglistadditionalitems> shoppinglistadditionalitems { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<userlist> userlist { get; set; }
        public virtual DbSet<userlistindex> userlistindex { get; set; }
        public virtual DbSet<userliststypes> userliststypes { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<usershoppinglist> usershoppinglist { get; set; }
        public virtual DbSet<usertypes> usertypes { get; set; }
        public virtual DbSet<recipesfavorits> recipesfavorits { get; set; }
        public virtual DbSet<shoppinglists> shoppinglists { get; set; }
    }
}
