//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyBuyListEntities : DbContext
    {
        public MyBuyListEntities()
            : base("name=MyBuyListEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CourseType> CourseTypes { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<FoodCategory> FoodCategories { get; set; }
        public virtual DbSet<GeneralItem> GeneralItems { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MBLSetting> MBLSettings { get; set; }
        public virtual DbSet<MCategory> MCategories { get; set; }
        public virtual DbSet<MealRecipe> MealRecipes { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<MealType> MealTypes { get; set; }
        public virtual DbSet<MeasurementUnit> MeasurementUnits { get; set; }
        public virtual DbSet<MeasurementUnitsConvert> MeasurementUnitsConverts { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuType> MenuTypes { get; set; }
        public virtual DbSet<MissingListDetail> MissingListDetails { get; set; }
        public virtual DbSet<MissingList> MissingLists { get; set; }
        public virtual DbSet<NutCategory> NutCategories { get; set; }
        public virtual DbSet<NutItem> NutItems { get; set; }
        public virtual DbSet<NutValue> NutValues { get; set; }
        public virtual DbSet<ReciepList> ReciepLists { get; set; }
        public virtual DbSet<ReciepListDetail> ReciepListDetails { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<RecipesInShoppingList> RecipesInShoppingLists { get; set; }
        public virtual DbSet<SavedList> SavedLists { get; set; }
        public virtual DbSet<SavedListDetail> SavedListDetails { get; set; }
        public virtual DbSet<ShopDepartment> ShopDepartments { get; set; }
        public virtual DbSet<ShoppingListAdditionalItem> ShoppingListAdditionalItems { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserList> UserLists { get; set; }
        public virtual DbSet<UserListsType> UserListsTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserShoppingList> UserShoppingLists { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<DS_Forum> DS_Forum { get; set; }
        public virtual DbSet<DS_ForumAdmin> DS_ForumAdmin { get; set; }
        public virtual DbSet<DS_ForumLog> DS_ForumLog { get; set; }
        public virtual DbSet<DS_ForumMessages> DS_ForumMessages { get; set; }
        public virtual DbSet<RecipesFavorit> RecipesFavorits { get; set; }
        public virtual DbSet<ShoppingList> ShoppingLists { get; set; }
    }
}
