//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.MealRecipes = new HashSet<MealRecipe>();
            this.RecipesInShoppingLists = new HashSet<RecipesInShoppingList>();
            this.Menus = new HashSet<Menu>();
            this.Categories = new HashSet<Category>();
            this.Users = new HashSet<User>();
        }
    
        public int RecipeId { get; set; }
        public string RecipeName { get; set; }
        public bool IsPublic { get; set; }
        public int Servings { get; set; }
        public string PreparationMethod { get; set; }
        public string Remarks { get; set; }
        public string Source { get; set; }
        public string MediaLink { get; set; }
        public int SortOrder { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Tools { get; set; }
        public bool IsApproved { get; set; }
        public byte[] Picture { get; set; }
        public string VideoLink { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public Nullable<int> DifficultyLevel { get; set; }
        public Nullable<int> PreperationTime { get; set; }
        public Nullable<int> CookingTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealRecipe> MealRecipes { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipesInShoppingList> RecipesInShoppingLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
