//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipes()
        {
            this.mealrecipes = new HashSet<mealrecipes>();
            this.recipesinshoppinglist = new HashSet<recipesinshoppinglist>();
            this.menus = new HashSet<menus>();
            this.users1 = new HashSet<users>();
        }
    
        public int RecipeId { get; set; }
        public string RecipeName { get; set; }
        public bool IsPublic { get; set; }
        public int Servings { get; set; }
        public string PreparationMethod { get; set; }
        public string Remarks { get; set; }
        public string Source { get; set; }
        public string MediaLink { get; set; }
        public int SortOrder { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Tools { get; set; }
        public bool IsApproved { get; set; }
        public byte[] Picture { get; set; }
        public string VideoLink { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public Nullable<int> DifficultyLevel { get; set; }
        public Nullable<int> PreperationTime { get; set; }
        public Nullable<int> CookingTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mealrecipes> mealrecipes { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipesinshoppinglist> recipesinshoppinglist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menus> menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users> users1 { get; set; }
    }
}
