//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipesinshoppinglist
    {
        public int RECIPE_ID { get; set; }
        public Nullable<int> SERVINGS { get; set; }
        public int USER_ID { get; set; }
    
        public virtual recipes recipes { get; set; }
        public virtual users users { get; set; }
    }
}
