//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlist
    {
        public int LIST_TYPE { get; set; }
        public int FOOD_ID { get; set; }
        public int USER_ID { get; set; }
        public string FOOD_NAME { get; set; }
        public Nullable<int> MEASURMENT_ID { get; set; }
        public string MEASUREMENT_NAME { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<bool> CAN_DELETE { get; set; }
        public byte[] IMAGE { get; set; }
    
        public virtual userliststypes userliststypes { get; set; }
    }
}
