//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyList.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlistindex
    {
        public int LIST_ID { get; set; }
        public int LIST_TYPE { get; set; }
        public string LIST_NAME { get; set; }
        public int OWNER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
